---
title: "annual_summary"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/slewa/Projects/heat_stress")

library(tidyverse)
library(readxl)
library(knitr)
library(kableExtra)
library(purrr)
library(furrr)
library(boot)
library(lme4)
library(ICC) 
library(dotwhisker)
library(broom)
library(car)
library(reshape2)
library(sjPlot)
library(readxl)
library(broom.mixed)
library(bbmle)
library(glmmTMB)
library(performance)
library(MASS)
library(mgcv)
library(gridExtra)
library(tableone)
library(corrr)
library(psych)
library(zoo)
library(flextable)

```

Annual models from DMED data.

```{r load_datasets, message = FALSE}

joined_hsi <-
  read_rds("data/joined_hsi.rds")





canopy_stats <-
  read_rds("data/canopy_stats_na_reclassified.rds") %>% 
  mutate(installation_lower = janitor::make_clean_names(installation))

# Remove Fort Irwin/NTC due to low counts/rates and transient training
# Remove initial year of health outcomes (1990 for Hospitilizations, 1997 for Ambulatory)

hsi_data <-
  joined_hsi %>% 
    left_join(canopy_stats %>% 
                dplyr::select(installation_lower, mean_canopy),
              by = c("installation" = "installation_lower")) %>% 
    filter(!installation %in% "ntc_and_fort_irwin",
           !(type %in% "Hospitalizations" & year %in% 1990),
           !(type %in% "Ambulatory Data" & year %in% 1997)) %>% 
    mutate(installation = factor(installation, ordered = FALSE),
         index = factor(index, ordered = FALSE),
         type = factor(type, ordered = FALSE),
         bct = factor(bct), 
         installation = relevel(installation, ref = "fort_bliss"))

levels(hsi_data$installation)

summary(hsi_data)


hsi_select <- hsi_data %>% 
  filter(index %in% c("days_tmp_gt85pct_may_sep",              #relative, heat season
                      "days_wbgt_gt85pct_may_sep",             #relative, heat season
                      "days_heat_index_gt85pct_may_sep",       #relative, heat season
                      "tmp_mean_may_sep",                      #absolute, heat season
                      "heat_index_mean_may_sep",               #absolute, heat season
                      "wbgt_f_mean_may_sep",                   #absolute, heat season
                      "tmp_f_mean",                            #absolute, year-round
                      "heat_index_mean",                       #absolute, year-round
                      "wbgt_f_mean"))                          #absolute, year-round



hsi_select %>% 
  filter(type %in% "Hospitalizations", 
         index %in% "days_tmp_gt85pct_may_sep") %>% 
  group_by(installation) %>%
  dplyr::select(installation:value) %>% 
    pivot_wider(., names_from = year)


# Plots of heat indices over time
hsi_select %>% 
  filter(type %in% "Hospitalizations",
          !index %in% c("days_tmp_gt85pct_may_sep", "days_heat_index_gt85pct_may_sep", "days_wbgt_gt85pct_may_sep")) %>%
  ggplot(aes(x = year, y = value, color = installation)) +
    geom_point() +
    geom_smooth(method = lm, se = FALSE, size = 0.5) +
  facet_wrap(~index, scale = "free") + 
  theme_bw()


hsi_select %>% 
  filter(type %in% "Hospitalizations",
        index %in% c("days_tmp_gt85pct_may_sep", "days_heat_index_gt85pct_may_sep", "days_wbgt_gt85pct_may_sep")) %>%
  ggplot(aes(x = year, y = value, color = installation)) +
    geom_point() +
    geom_smooth(method = lm, se = FALSE, size = 0.5) +
  facet_wrap(~index, scale = "free") + 
  theme_bw()

  # all 9 together
hsi_select %>% 
  filter(type %in% "Hospitalizations") %>%
  ggplot(aes(x = year, y = value, color = installation)) +
    geom_point() +
    geom_smooth(method = lm, se = FALSE, size = 0.5) +
  facet_wrap(~index, scale = "free") + 
  theme_bw()

#ggsave("output/indices_by_installation.png")




# Boxplots


hsi_select %>% 
  filter(type %in% "Hospitalizations",
         !index %in% c("days_tmp_gt85pct_may_sep", "days_heat_index_gt85pct_may_sep", "days_wbgt_gt85pct_may_sep")) %>%
  group_by(year) %>% 
  summarise(mean_value = mean(value)) 

hsi_select %>% 
  filter(type %in% "Hospitalizations",
         !index %in% c("days_tmp_gt85pct_may_sep", "days_heat_index_gt85pct_may_sep", "days_wbgt_gt85pct_may_sep")) %>%
  group_by(installation, index) %>% 
  ggplot(aes(x = year, group = year, y = value)) +
    geom_boxplot() +
    facet_grid(~index)
    theme_bw()

hsi_select %>% 
  filter(type %in% "Hospitalizations",
         index %in% c("days_tmp_gt85pct_may_sep", "days_heat_index_gt85pct_may_sep", "days_wbgt_gt85pct_may_sep")) %>%
  group_by(installation, index) %>% 
  ggplot(aes(x = year, group = year, y = value)) +
    geom_boxplot() +
    facet_grid(~index)
    theme_bw()



```

Note: "days_tmp_gt95pct_may_sep", for each calendar day, compares mean daily temperature with 95th %-ile of 30-year (1990-2019) climatology for that day

## Tables

```{r}

# Table 1: HSI outcomes

hsi_select %>% 
  filter(index %in% "tmp_f_mean") %>% 
  dplyr::select(installation, type, year, count, rate) %>% 
  group_by(installation, type) %>%
  summarise(mean_count = mean(count),
            sd_count = sd(count),
            mean_rate = mean(rate),
            sd_rate = sd(rate)) %>% 
  pivot_wider(names_from = type, values_from = c(mean_count:sd_rate))



hsi_select %>% 
  filter(index %in% "tmp_f_mean") %>% 
  dplyr::select(installation, type, year, count, rate) %>% 
  group_by(installation, type) %>%
  summarise(mean_count = mean(count),
            sd_count = sd(count),
            mean_rate = mean(rate),
            sd_rate = sd(rate)) %>%
  mutate(count = paste0(round(mean_count, 2)," ", "(", round(sd_count, 2), ")"),
         rate = paste0(round(mean_rate, 2)," ", "(", round(sd_rate, 2), ")")) %>% 
  dplyr::select(installation, type, count, rate) %>% 
  pivot_wider(names_from = type, values_from = c(count, rate))

# Burden Table

hsi_select %>% 
  filter(index %in% "tmp_f_mean") %>% 
  dplyr::select(installation, type, year, burden) %>% 
  group_by(installation, type) %>%
  summarise(mean_burden = mean(burden) * 100,
            sd_burden = sd(burden) * 100) %>% 
 mutate(burden = paste0(round(mean_burden, 2)," ", "(", round(sd_burden, 2), ")")) %>% 
  dplyr::select(installation, type, burden) %>% 
  pivot_wider(names_from = type, values_from = burden)




# Table 2: Indices of Heat

hsi_select %>% 
  filter(type %in% "Hospitalizations") %>% 
  dplyr::select(installation, index, year, value) %>% 
  group_by(installation, index) %>%
  summarise(mean_value = mean(value),
            sd_value = sd(value)) %>%
  mutate(value = paste0(round(mean_value, 2)," ", "(", round(sd_value, 2), ")")) %>% 
  dplyr::select(installation, index, value) %>% 
  pivot_wider(names_from = index, values_from = value) %>% 
  View()

## Indices Correlation matrix
hsi_select %>% 
  filter(type %in% "Hospitalizations") %>% 
  dplyr::select(installation, index, year, value) %>% 
  group_by(installation, index) %>%
  summarise(mean_value = mean(value)) %>% 
  dplyr::select(installation, index, mean_value) %>% 
  pivot_wider(names_from = index, values_from = mean_value) %>% 
  ungroup() %>% 
  mutate(installation = as.character(installation)) %>% .[2:10] %>% 
  psych::pairs.panels()



```




## Temperature over time models

```{r}

tmp_lm_function = function(df) {
  df %>%
    lm(value ~ year, data = .)
}



hsi_select %>% 
  filter(type %in% "Hospitalizations") %>% 
  nest(data = year:mean_canopy) %>% 
  mutate(lm_tmp = map(data, tmp_lm_function),
         tidy =   map(lm_tmp, broom::tidy),
         glance = map(lm_tmp, broom::glance)) %>% 
  unnest(tidy) %>% 
  filter(term %in% "year") %>% 
  arrange(p.value)







# Slope estimate
tmp_slopes <-
  hsi_select %>% 
    filter(type %in% "Hospitalizations") %>% 
    nest(data = year:mean_canopy) %>% 
    mutate(lm_tmp = map(data, tmp_lm_function),
           tidy =   map(lm_tmp, broom::tidy),
           glance = map(lm_tmp, broom::glance))



# Temperature slope estimates (1991-2018)
tmp_slopes %>% 
    unnest(tidy) %>%
    dplyr::select(installation, index, term:p.value) %>% 
    filter(term %in% "year") 

# Significant positive slopes
tmp_slopes %>% 
    unnest(tidy) %>%
    dplyr::select(installation, index, term:p.value) %>% 
    filter(term %in% "year",
           p.value < 0.05) %>% 
    arrange(desc(estimate)) %>% View()




tmp_slopes %>% 
    unnest(tidy) %>% 
    filter(term %in% "year") %>% 
    group_by(index) %>% 
    ggplot() +
      geom_boxplot(aes(x = reorder(index, estimate), y = estimate)) +
      coord_flip()


# p-values    
hsi_select %>% 
  filter(type %in% "Hospitalizations") %>% 
  nest(data = year:mean_canopy) %>% 
  mutate(lm_tmp = map(data, tmp_lm_function),
         tidy =   map(lm_tmp, broom::tidy),
         glance = map(lm_tmp, broom::glance)) %>% 
  unnest(tidy) %>% 
  filter(term %in% "year") %>% 
  group_by(index) %>% 
  ggplot() +
    geom_boxplot(aes(x = reorder(index, p.value), y = p.value)) +
    geom_hline(yintercept = 0.05, color = "blue") +
    coord_flip() 




## Full list of indices
tmp_slopes_full <-
  hsi_data %>% 
    filter(type %in% "Hospitalizations") %>% 
    nest(data = year:mean_canopy) %>% 
    mutate(lm_tmp = map(data, tmp_lm_function),
           tidy =   map(lm_tmp, broom::tidy),
           glance = map(lm_tmp, broom::glance))

tmp_slopes_full %>% 
    unnest(tidy) %>%
    dplyr::select(installation, index, term:p.value) %>% 
    filter(term %in% "year") %>% 
    arrange(desc(estimate))

# Significant positive slopes
tmp_slopes_full %>% 
    unnest(tidy) %>%
    dplyr::select(installation, index, term:p.value) %>% 
    filter(term %in% "year",
           p.value < 0.05) %>% 
    arrange(desc(estimate)) %>% View()  #View() to identify significant negative estimates


tmp_slopes_full %>% 
    unnest(tidy) %>% 
    filter(term %in% "year") %>% 
    group_by(index) %>% 
    ggplot() +
      geom_boxplot(aes(x = reorder(index, estimate), y = estimate)) +
      coord_flip()


# Additional indices


tmp_slopes_addl <-
  may_sep_day_hour_join %>%     # from "bootstrap2.Rmd"
    filter(type %in% "Hospitalizations") %>%
    dplyr::select(installation, index, everything()) %>% 
    nest(data = year:value) %>% 
    mutate(lm_tmp = map(data, tmp_lm_function),
           tidy =   map(lm_tmp, broom::tidy),
           glance = map(lm_tmp, broom::glance))
  
# Significant positive slopes
tmp_slopes_addl %>% 
    unnest(tidy) %>%
    dplyr::select(installation, index, term:p.value) %>% 
    filter(term %in% "year",
           p.value < 0.05) %>% 
    arrange(desc(estimate)) 

599/1040
  
```

- Out of 90 index/location combinations, 43 had a positive (significant at alpha = 0.05) slope; none had a significant negative slope

## Plot HSI

```{r}
plot_amb_hsi <-
  hsi_select %>% 
    filter(type == "Ambulatory Data") %>% 
   ggplot(aes(x = year, y = rate, color = installation)) +
      geom_point() +
      geom_line() +
      labs(
        title = "Army Ambulatory Rates - HSI",
        x = "Year",
        y = "All ICD rate (per 1,000 persons per year)"
      ) +
      theme_bw() +
      theme(strip.text = element_text(size = 6)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))


plot_hosp_hsi <-
  hsi_select %>% 
    filter(type == "Hospitalizations") %>% 
   ggplot(aes(x = year, y = rate, color = installation)) +
      geom_point() +
      geom_line() +
      labs(
        title = "Army Hospitalization Rates - HSI",
        x = "Year",
        y = "All ICD rate (per 1,000 persons per year)"
      ) +
      theme_bw() +
      theme(strip.text = element_text(size = 6)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))



plot_rme_hsi <-
  hsi_select %>% 
    filter(type == "Reportable Events") %>% 
   ggplot(aes(x = year, y = rate, color = installation)) +
      geom_point() +
      geom_line() +
      labs(
        title = "Army Reportable Event Rates - HSI",
        x = "Year",
        y = "All ICD rate (per 1,000 persons per year)"
      ) +
      theme_bw() +
      theme(strip.text = element_text(size = 6)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))

gridExtra::grid.arrange(plot_amb_hsi, plot_hosp_hsi, plot_rme_hsi, nrow = 1)




# Facet wrap

# HSI
 hsi_select %>% 
   ggplot(aes(x = year, y = rate, color = installation)) +
      geom_point() +
      geom_line() +
      labs(
        title = "Heat Stress Illness Rates",
        x = "Year",
        y = "HSI rate (per 1,000 persons per year)"
      ) +
      facet_grid(~type) +
      theme_bw() +
      theme(strip.text = element_text(size = 6)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))

# All ICD
 hsi_select %>% 
   ggplot(aes(x = year, y = rate_overall, color = installation)) +
      geom_point() +
      geom_line() +
      labs(
        title = "All-ICD Code Rates",
        x = "Year",
        y = "All-ICD rate (per 1,000 persons per year)"
      ) +
      facet_grid(~type) +
      theme_bw() +
      theme(strip.text = element_text(size = 6)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

## By Installation Tables


```{r}

#indices

wider_fun = function(df) {
  pivot_wider(df, names_from = year, values_from = value)
}



# get group keys
group_name <- hsi_data %>% 
  group_keys(installation) %>% 
  .$installation


index_tables <-    
  hsi_data %>%
    filter(type %in% "Hospitalizations",
           year >= 2008) %>%
    mutate(value = format(round(value, 2), nsmall = 2)) %>% 
    dplyr::select(installation, index, year, value) %>%
    group_split(installation, keep = FALSE) %>%
    purrr::map(wider_fun) %>% 
    setNames(group_name)



index_tables[[1]] %>% 
  flextable() %>% 
  flextable::fontsize(., part = "all", size = 6) %>% 
  flextable::padding(., padding = 0, part = "body") %>%
  flextable::bold(., part = "header") %>% 
  flextable::autofit() %>% 
  print(., preview = "docx")



```




```{r}
# Variability over time 
# hsi_data %>% 
#   filter(index %in% "tmp_f_sd",
#          type %in% "Hospitalizations") %>% 
#    ggplot(aes(x = year, y = value, color = installation)) +
#       geom_point() +
#       geom_line() +
#       labs(
#         title = "Temperature SD",
#         x = "Year",
#         y = "SD, Temp (°F)"
#       ) +
#       facet_grid(~type) +
#       theme_bw() +
#       theme(axis.text.x = element_text(angle = 90, hjust = 1))
#   
# hsi_data %>% 
#   filter(index %in% "heat_index_sd",
#          type %in% "Hospitalizations") %>% 
#    ggplot(aes(x = year, y = value, color = installation)) +
#       geom_point() +
#       geom_line() +
#       labs(
#         title = "Temperature SD",
#         x = "Year",
#         y = "SD, Temp (°F)"
#       ) +
#       facet_grid(~type) +
#       theme_bw() +
#       theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

