---
title: "installation_index_trends"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(purrr)
library(ggplot2)
```




```{r import}



annual_tables_list <- 
  read_rds("data/annual_tables_list.rds")


army10_list <-
  annual_tables_list %>% 
  dplyr::filter(installation %in% 
                  c("fort_bliss", "fort_benning_ga", "fort_bragg", "fort_campbell", "fort_hood", "fort_jackson",
                    "fort_leonard_wood", "fort_polk", "fort_riley", "fort_stewart")) %>% 
  mutate(installation = dplyr::recode(installation, 
                                      fort_bliss   = "Fort Bliss",
                                      fort_bragg   = "Fort Bragg",
                                      fort_campbell   = "Fort Campbell",
                                      fort_hood   = "Fort Hood",
                                      fort_jackson   = "Fort Jackson",
                                      fort_leonard_wood = "Fort Leonard Wood",
                                      fort_polk   = "Fort Polk",
                                      fort_riley   = "Fort Riley",
                                      fort_stewart   = "Fort Stewart",
                                      fort_benning_ga = "Fort Benning"))

army10_list$data[1]


```


Mean annual temperature
```{r}

tmp_mean_to_gg <-
  army10_list %>% 
    unnest(data) %>%
    rename(Installation = installation) %>% 
    filter(index %in% "tmp_f_mean") %>%
    dplyr::select(-index) %>%
    pivot_longer(
      cols = -c(Installation),
      names_to = "Year",
      values_to = "Mean Temperature (째F)",
      values_drop_na = TRUE
    ) %>% 
  mutate(Year = as.numeric(Year)) %>% 
  filter(Year > 1990 & Year < 2019)
 
# Installation by color, shapr
tmp_mean_to_gg %>% 
  ggplot(aes(x = Year, y = `Mean Temperature (째F)`, color = Installation, group = Installation, shape = Installation)) +
    geom_point() +
    geom_line() +
    geom_smooth(method = "lm", alpha = 0.1, size = 0.5) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    theme(legend.position = "bottom") +
    theme(legend.title = element_blank()) +
    scale_shape_manual(values = seq(0,10)) +
    guides(color = guide_legend(nrow = 3),
           shape = guide_legend(nrow = 3)) 

# All points combined, overall trend

tmp_mean_to_gg %>%
  ungroup() %>% 
  ggplot(aes(x = Year, y = `Mean Temperature (째F)`)) +
    geom_point() +
    geom_smooth(method = "lm", alpha = 0.25) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) 


# Facet wrap by installation

tmp_mean_to_gg %>% 
  ggplot(aes(x = Year, y = `Mean Temperature (째F)`)) +
    geom_point() +
    geom_line() +
    geom_smooth(method = "lm", alpha = 0.1, size = 0.5) +
    facet_wrap(~ Installation) +  
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
    theme(legend.position = "bottom") 
    




```

